name: pr build

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: actions/setup-java@v2
        with: 
         java-version: 11 
         distribution: 'zulu' 
         cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml 
      
